-- Lab 3, assignment 2
-- Team: FT_7
-- Date: 10.09.2015
-- Software Testing, Master Software Engineering (2015), University Of Amsterdam

module Assignment2

where

import Lecture3
import ArbitraryForm

prop_Parse f = [f] == (parse $ show f)
    where types = f::Form

{-
 - Time spent:
 - Understanding parse: 15min
 - Implementing ArbitraryForm: 3hours
 - 
 - Our test method uses QuickCheck. The arbitrary implementation can be found in ArbitraryForm.hs
 - the prop_Parse function tests if the parse function returns the same Form as was generated by QuickCheck.
 - Usage "check prop_Parse" or "vCheck prop_Parse" (for verbose output).
 -
 -}
